compatibility_date = "2024-08-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ccms-dev"
database_id = "cd007fb6-9ad9-417b-a03f-1612c1a9ab23"
migrations_dir = "./drizzle"
